language: ruby
script: 'bundle exec rake ci'
services:
  - elasticsearch
rvm:
  - 1.9.3
  - 2.0.0
  - rbx
  - jruby
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
