language: ruby
script: 'bundle exec rake ci'
services:
  - elasticsearch
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: rbx-18mode # Json lib is defunct
notifications:
  irc: "irc.freenode.org#datamapper"
  email:
    - mbj@seonic.net
