---
UncommunicativeParameterName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
TooManyMethods:
  max_methods: 10
  exclude:
  - Esearch::Command # 12 methods, TODO: Bring down to 10. Extraction of Response class!
  - Esearch::Request # 4 instance variables. Acceptable as this is a DTO
  enabled: true
  max_instance_variables: 3
UncommunicativeMethodName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^[a-z]$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
LongParameterList:
  max_params: 2
  exclude:
  - Esearch::Request#initialize # 4 parameters, acceptable it is a DTO
  enabled: true
  overrides: {}
FeatureEnvy:
  exclude: []
  enabled: true
ClassVariable:
  exclude: []
  enabled: true
BooleanParameter:
  exclude: []
  enabled: true
IrresponsibleModule:
  exclude: []
  enabled: true
UncommunicativeModuleName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
NestedIterators:
  ignore_iterators: []
  exclude:
  - Esearch::Presenter#self.expose_tagged_collection # 2 levels
  enabled: true
  max_allowed_nesting: 1
TooManyStatements:
  max_statements: 5
  exclude:
  - Esearch::Connection#run
  enabled: true
DuplicateMethodCall:
  allow_calls:
  - util.debug
  exclude: []
  enabled: true
  max_calls: 1
UtilityFunction:
  max_helper_calls: 1
  exclude: []
  enabled: true
Attribute:
  exclude: []
  enabled: false
UncommunicativeVariableName:
  accept: []
  exclude: []
  enabled: true
  reject:
  - !ruby/regexp /^.$/
  - !ruby/regexp /[0-9]$/
  - !ruby/regexp /[A-Z]/
RepeatedConditional:
  exclude: []
  enabled: true
  max_ifs: 2
DataClump:
  exclude: []
  enabled: true
  max_copies: 1
  min_clump_size: 3
ControlParameter:
  exclude:
  - Esearch::Index#read
  enabled: true
LongYieldList:
  max_params: 1
  exclude: []
  enabled: true
UnusedParameters:
  exclude:
    - Esearch::NullLogger#self.debug
    - Esearch::NullLogger#self.error
    - Esearch::NullLogger#self.info
    - Esearch::NullLogger#self.warn
